# Site settings
description: Whittington U: Real World Training for Real Life Situations
baseurl: "http://whittingtonu.github.io/WU-Site" # the subpath of your site, e.g. /blog
url: "http://whittingtonu.github.io/WU-Site" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Whittington U
user_description: Anon Developer at Lorem Ipsum Dolor
user_title: Anon Developer
email: anon@anon.com
twitter_username: whittingtonu
github_username:  whittingtonu
gplus_username:  lorem_ipsum
disqus_username: whittingtonu

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
